name: "QA / Bug Report"
description: "Template to report QA issues or bugs. Provide a summary, steps to reproduce, expected vs actual behavior, and any attachments or logs."
title: "Issue Summary"
    validations:
      required: true
labels:
  - "triage"
  - "qa"
  - "bug"

body:
  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      description: "Choose the severity of the issue."
      options:
        - "0 (Critical)"
        - "1 (Severe)"
        - "2 (High)"
        - "3 (Med)"
        - "4 (Low)"
        - "5 (Document, Request, or Suggestion)"
      default: 2
    validations:
      required: true

  - type: input
    id: build_number
    attributes:
      label: "Build Number"
      description: "Enter the build number (numeric)."
      placeholder: "e.g. 20260114 or 1234"
    validations:
      required: false

- type: textarea
id: description
attributes:
label: "Issue Description"
description: "Provide a detailed description of the issue. Include context, what you expected to happen, and any other relevant notes."
placeholder: |
"Detailed description of the issue"
validations:
required: false

- type: textarea
id: steps_to_reproduce
attributes:
label: "Steps to Reproduce"
description: "Use the numbered template below. Add additional steps by continuing the numbering."
placeholder: |
" 1.
2.
3.
(Add more numbered lines as needed)"
validations:
required: false

- type: input
id: location_of_issue
attributes:
label: "Location of issue (page / section)"
description: "Where in the app or webapp did this occur? Page, section, or workflow."
placeholder: "e.g., Settings > Profile > Change Password"
validations:
required: false

- type: textarea
id: other_files
attributes:
label: "Crash log or other file (paste logs or provide links)"
description: "Paste important log excerpts here, or provide links to full logs (Gist, cloud storage, etc.). For very large logs, link to a Gist or upload and share a link."
validations:
required: false

- type: input
id: os_environment
attributes:
label: "OS / Environment"
description: "Operating system, OS version, device, browser and version (if applicable)."
placeholder: "e.g., Android 13 - Pixel 6; iOS 16.2 - iPhone 12; Windows 11, Chrome 114"
validations:
required: false

